package com.app.xeross.infoxer.utils

const val SWITCH_STATE_DARK_MODE = "SWITCH_STATE_DARK_MODE"
const val SHARED_PREFERENCES = "SHARED_PREFERENCES"
const val TITLE_CATEGORY = "TITLE_CATEGORY"
const val IMAGE_CATEGORY = "IMAGE_CATEGORY"

// AUTH
const val RC_SIGN_IN = 555
const val PICK_IMAGE_REQUEST = 89

// COLLECTIONS
const val USERS_COLLECTION = "users"