package com.app.xeross.infoxer.utils

const val SWITCH_STATE_DARK_MODE = "SWITCH_STATE_DARK_MODE"
const val SHARED_PREFERENCES = "SHARED_PREFERENCES"
const val TITLE_CATEGORY = "TITLE_CATEGORY"
const val IMAGE_CATEGORY = "IMAGE_CATEGORY"